name: domain checker

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 * 13-17 5 *'  # At minute 30 on every day-of-month from 13 through 17 in May.

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python src/check_domain.py
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          WHOIS_SERVER: ${{ secrets.WHOIS_SERVER }}
          NTFY_CHANNEL: ${{ secrets.NTFY_CHANNEL }}
